# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1prJKDyCIalwEr-9ZJS2l9qLdDvHaLO1s
"""

# 🧩 Problem: Subarray Sum Equals K (LeetCode 560)
# ------------------------------------------------
# Given an array of integers nums and an integer k,
# return the total number of contiguous subarrays whose sum equals k.

# Example 1:
# Input: nums = [1,1,1], k = 2
# Output: 2
#
# Example 2:
# Input: nums = [1,2,3], k = 3
# Output: 2


# ------------------------------------------------
# Approach 1 — Prefix Sum + HashMap (Optimal)
# ------------------------------------------------
# Idea:
#   Let prefix[i] = sum(nums[:i]).
#   For each running sum 's', if (s - k) appeared before,
#   that means there exists a subarray summing to k.
#
# Time:  O(n)
# Space: O(n)
# Works even when numbers are negative.

from collections import defaultdict

class Solution:
    def subarraySum(self, nums, k):
        freq = defaultdict(int)
        freq[0] = 1  # base case: empty prefix
        s = ans = 0
        for x in nums:
            s += x
            ans += freq[s - k]   # subarrays ending here with sum k
            freq[s] += 1
        return ans


# ------------------------------------------------
# Approach 2 — Brute Force (Two Loops)
# ------------------------------------------------
# Idea:
#   For each starting index i, expand rightwards and keep a running sum.
#   Count subarrays where the sum equals k.
#
# Time:  O(n²)
# Space: O(1)

class Solution:
    def subarraySum(self, nums, k):
        ans = 0
        for i in range(len(nums)):
            s = 0
            for j in range(i, len(nums)):
                s += nums[j]
                if s == k:
                    ans += 1
        return ans


# ------------------------------------------------
# Approach 3 — Prefix Array + Range Sum
# ------------------------------------------------
# Idea:
#   Build a prefix array where prefix[i] = sum(nums[:i]).
#   Then for any range (i, j), subarray sum = prefix[j+1] - prefix[i].
#
# Time:  O(n²)
# Space: O(n)

class Solution:
    def subarraySum(self, nums, k):
        n = len(nums)
        prefix = [0] * (n + 1)
        for i in range(n):
            prefix[i + 1] = prefix[i] + nums[i]
        ans = 0
        for i in range(n):
            for j in range(i, n):
                if prefix[j + 1] - prefix[i] == k:
                    ans += 1
        return ans


# ------------------------------------------------
# Approach 4 — Sliding Window (Only for Non-Negative nums)
# ------------------------------------------------
# Idea:
#   Use two pointers. Expand the window until sum >= k.
#   If sum > k, shrink from left.
#   Works only when all numbers are non-negative (since sum is monotonic).
#
# Time:  O(n)
# Space: O(1)

class Solution:
    def subarraySumNonNegative(self, nums, k):
        l = s = ans = 0
        for r, x in enumerate(nums):
            s += x
            while s > k and l <= r:
                s -= nums[l]
                l += 1
            if s == k:
                ans += 1
        return ans


# ------------------------------------------------
# Pattern Summary
# ------------------------------------------------
# Pattern: Prefix Sum + Frequency Counting
# Key insight:
#   For each prefix sum s, the number of subarrays ending at this index
#   that sum to k equals the count of previous prefix sums = s - k.
# Gotcha:
#   Always initialize freq[0] = 1 to count subarrays starting from index 0.

